package scala:example;

interface api {
    resource counter {
        constructor(name: string);
        increment: func(delta: s32);
        get: func() -> s32;
        name: func() -> string;

        get-all: static func() -> list<tuple<string, s32>>;
    }

    get-counters: func() -> list<counter>;
}

world example {
    export api;

  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:clocks/wall-clock@0.2.0;
  import wasi:io/poll@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:cli/environment@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  import wasi:logging/logging;
}